site_name: MORAI SIM Air - Cirrus
site_url: https://morai-docs.github.io/simair-cirrus
site_description: Project documentation with Markdown.
site_author: MORAI Engineering Service Team

repo_url: https://github.com/morai-docs/simair-cirrus
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Release Note: release-notes.md

  - About this Documents:
    - Revision History: about/revision-history.md
    - Overview: about/overview.md
    - Terminology and Conventions: about/terms-conventions.md
    
  - Introduction: 
    - About Morai SIM Air: intro/morai-simair.md

  - Gettign Started: 
    - Installation: getting-started/installation.md
    - User Interface: getting-started/ui.md

  - Using MORAI SIM Air:
    - User Guide: user-guide/
    - Basic Controls: user-guide/basic-controls.md
    - Network Configurations: user-guide/network.md
    - Sensor Setting: user-guide/sensors.md
    - Useful Functions: user-guide/useful.md
  



theme: 
  name: readthedocs
  locale: en
  highlightjs: true
  #custom_dir: custom_theme


extra_css: [custom.css]

markdown_extensions:
  - smarty
  - toc:
      permalink: 
  - admonition: {}
  - sane_lists
  - attr_list
  - def_list
  - tables
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 <a href="https://www.morai.ai">MORAI Inc.</a> Maintained by the <a href="https://github.com/morai-docs">MORAI-Docs Team</a>

# remote_branch: main

#  features:
#    - navigation.expand
#  name: material
