site_name: My MkDocs


nav:
  - Home: '../'
  - index.md
  - Release Note: '../'
  
theme: 
  name: readthedocs
  #custom_dir: custom_theme

extra_css: [custom.css]

markdown_extensions:
    - smarty
#  features:
#    - navigation.expand
#  name: material
